admin:
    port: 9990

routers:
  - protocol: http
    label: hello
    dtab: /svc => /$/inet/hello/80
    servers:
      - port: 8080
        ip: 0.0.0.0

  - protocol: http
    label: router1
    dtab: /svc => /$/inet/127.1/9001
    servers:
    - port: 9000
  - protocol: http
    label: router2
    dtab: /svc => /$/inet/127.1/9002
    servers:
    - port: 9001
  - protocol: http
    label: router3
    dtab: /svc => /$/inet/127.1/9990
    servers:
    - port: 9002

telemetry:
  - kind: io.l5d.zipkin
    host: zipkin
    port: 9410
    sampleRate: 1.0
